// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7BFqMfEwmYR5j0U3-yghM_CtsZ00Exb0',
    appId: '1:858700310760:web:3dbd189fa1328452ad415d',
    messagingSenderId: '858700310760',
    projectId: 'seekhobuddy-8e7d5',
    authDomain: 'seekhobuddy-8e7d5.firebaseapp.com',
    storageBucket: 'seekhobuddy-8e7d5.appspot.com',
    measurementId: 'G-WKDTQYJ36W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-zbWeXCne0hZ0U4JOakrpIfV-uVNwe7Q',
    appId: '1:858700310760:android:1002e39d55d17d76ad415d',
    messagingSenderId: '858700310760',
    projectId: 'seekhobuddy-8e7d5',
    storageBucket: 'seekhobuddy-8e7d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC31J_kkKj_INAO1xVHTXZUy8s8rL7FefQ',
    appId: '1:858700310760:ios:40482ce39c3a7140ad415d',
    messagingSenderId: '858700310760',
    projectId: 'seekhobuddy-8e7d5',
    storageBucket: 'seekhobuddy-8e7d5.appspot.com',
    iosBundleId: 'com.app.seekhobuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC31J_kkKj_INAO1xVHTXZUy8s8rL7FefQ',
    appId: '1:858700310760:ios:43835163727c9e98ad415d',
    messagingSenderId: '858700310760',
    projectId: 'seekhobuddy-8e7d5',
    storageBucket: 'seekhobuddy-8e7d5.appspot.com',
    iosBundleId: 'com.example.seekhobuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7BFqMfEwmYR5j0U3-yghM_CtsZ00Exb0',
    appId: '1:858700310760:web:927e445ba5ec917cad415d',
    messagingSenderId: '858700310760',
    projectId: 'seekhobuddy-8e7d5',
    authDomain: 'seekhobuddy-8e7d5.firebaseapp.com',
    storageBucket: 'seekhobuddy-8e7d5.appspot.com',
    measurementId: 'G-ND7KV2BYZP',
  );
}
